name: test conan

on:
    workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: cache dependencies
      uses: actions/cache@v4
      id: cache
      with:
        path: ${{ github.workspace }}/${{ env.INSTALL_LOCATION }}
        key: ${{ runner.os }}-dependencies

    - name: install conan
      run: |
        pip install conan
        conan profile detect --force
        ls -a
        ls ~ -a

    - name: install conan packages
      if: ${{ steps.cache.output.cache-hit != 'true' }}
      run: conan install conanfile.txt --build=missing
            
