name: test conan

on:
    workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
    
    - name: cache dependencies
      uses: actions/cache@v4
      id: cache
      with:
        path: |
          ~/.conan2/
          ${{github.workspace}}/conan
          
          
        key: ${{ runner.os }}-dependencies

    - name: install conan
      run: |
        wget https://github.com/conan-io/conan/releases/download/2.0.17/conan-linux-64.tar.gz
        tar -xvf conan-linux-64.tar.gz
        conan profile detect --force

    - name: install conan packages
    #  if: ${{ steps.cache.output.cache-hit != 'true' }}
      run: conan install conanfile.txt --build=missing
            
