name: test conan

on:
    workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
    
    - name: cache dependencies
      uses: actions/cache@v4
      id: cache
      with:
        path: ~/.conan2/
        key: ${{ runner.os }}-dependencies

    - name: setup pip
      uses: actions/setup-python@v5
      with:
        cache: 'pip' # caching pip dependencies
        
    - name: install conan
      run: pip install conan

    - name: install conan packages
    #  if: ${{ steps.cache.output.cache-hit != 'true' }}
      run: conan install conanfile.txt --build=missing
            
